version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: hatka
      POSTGRES_PASSWORD: hatkapass
      POSTGRES_DB: hatkadb
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
